### ISSUE TITLE
Different Synth: mouse click v key press

### ISSUE THREAD

**Issue by jmdahle** [spianoDev/react-music#9]
Mouse clicks use selected synth.  However, key presses use AMSynth (and does not change)

**Comment by 8ctopotamus** [comment]
@jmdahle Good catch! 

We just need to tweak *components/synth/index.js* so that `useEffect` watches `state.instrument` in the dependencies array instead of `state.theme`. Then it should re-render on instrument change and load the new synth. Lmk if that works!

https://github.com/spianoDev/react-music/blob/jd/src/components/synth/index.js

![image](https://user-images.githubusercontent.com/17594101/95003768-2fd40200-05a8-11eb-8352-080962488a94.png)

**Comment by jmdahle** [comment]
Missed that one!  Much better.

**Comment by jmdahle** [comment]
Issue not completely resolved :(

When a different synth is selected, I expect the next note I play using the keyboard to use the newly selected synth.

Exception: When I select a synth other than AMSynth (the default), if I play the next note using the keyboard, the synth will change back to AMSynth.  (If I first play a new note using a mouse click, playing subsequent notes using the keyboard REMAINS on the newly-selected synth, as expected)
